lts:
  jobclient:
    cluster-name: cluster-test
    registry-address: redis://127.0.0.1:6379
    node-group: group-test
    use-retry-client: true
    configs:
      job:
        fail:
          store: mapdb

spring:
  application:
    name: lts-jobclient
server:
  port: 9000
